 <img src="https://github.com/MahendraCherukupalli/The-Sparks-Foundation-Internship/blob/master/wpl_badge1.png?raw=true"/>

## Steps:
- Import Libraries
- Get the Data
- Data Preprocessing
- Train-Test Split
- Scalling the Data
- Creating and Training the Model
- Predictions
- Residual Analysis
- Evaluating the modelm

**Let's get started!**

# Import Libraries

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns  
import matplotlib.pyplot as plt  
%matplotlib inline

# Get the data

In [3]:
data=pd.read_csv("matches.csv")
data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [4]:
data.shape

(756, 18)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
id                 756 non-null int64
season             756 non-null int64
city               749 non-null object
date               756 non-null object
team1              756 non-null object
team2              756 non-null object
toss_winner        756 non-null object
toss_decision      756 non-null object
result             756 non-null object
dl_applied         756 non-null int64
winner             752 non-null object
win_by_runs        756 non-null int64
win_by_wickets     756 non-null int64
player_of_match    752 non-null object
venue              756 non-null object
umpire1            754 non-null object
umpire2            754 non-null object
umpire3            119 non-null object
dtypes: int64(5), object(13)
memory usage: 106.4+ KB

In [6]:
data.describe()

                 id       season  dl_applied  win_by_runs  win_by_wickets
count    756.000000   756.000000  756.000000   756.000000      756.000000
mean    1792.178571  2013.444444    0.025132    13.283069        3.350529
std     3464.478148     3.366895    0.156630    23.471144        3.387963
min        1.000000  2008.000000    0.000000     0.000000        0.000000
25%      189.750000  2011.000000    0.000000     0.000000        0.000000
50%      378.500000  2013.000000    0.000000     0.000000        4.000000
75%      567.250000  2016.000000    0.000000    19.000000        6.000000
max    11415.000000  2019.000000    1.000000   146.000000       10.000000

In [7]:
data1=pd.read_csv("deliveries.csv")
data1.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [8]:
data1.shape

(179078, 21)

In [9]:
data1.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000
mean,1802.252957,1.482952,10.162488,3.615587,0.000452,0.036721,0.004936,0.021136,0.004183,0.000056,1.246864,0.067032,1.313897
std,3472.322805,0.502074,5.677684,1.806966,0.021263,0.251161,0.116480,0.194908,0.070492,0.016709,1.608270,0.342553,1.605422
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,190.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,379.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,567.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,11415.000000,5.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,7.000000,7.000000,10.000000

# Data Preprocessing

In [10]:
# checking for null values...
data.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [11]:
data1.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [12]:
data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [13]:
Rcb=data["team1"]=='Royal Challengers Bangalore'
Kkr=data["team1"]=='Kolkata Knight Riders'
Rcb1=data["team2"]=='Royal Challengers Bangalore'
Kkr1=data["team2"]=='Kolkata Knight Riders'

In [14]:
rdf=data[(Rcb & Kkr1)|(Rcb1 & Kkr)]

In [15]:
rdf

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
26,27,2017,Kolkata,2017-04-23,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,82,0,NM Coulter-Nile,Eden Gardens,CB Gaffaney,CK Nandan,NaN
44,45,2017,Bangalore,2017-05-07,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,6,SP Narine,M Chinnaswamy Stadium,AY Dandekar,C Shamshuddin,NaN
59,60,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
87,88,2008,Kolkata,2008-05-08,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,5,0,SC Ganguly,Eden Gardens,Asad Rauf,IL Howell,NaN
133,134,2009,Durban,2009-04-29,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,normal,0,Royal Challengers Bangalore,0,5,MV Boucher,Kingsmead,MR Benson,TH Wijewardene,NaN
155,156,2009,Centurion,2009-05-12,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,LRPL Taylor,SuperSport Park,M Erasmus,SS Hazare,NaN
177,178,2010,Kolkata,2010-03-14,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,MK Tiwary,Eden Gardens,HDPK Dharmasena,AM Saheba,NaN
216,217,2010,Bangalore,2010-04-10,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,7,R Vinay Kumar,M Chinnaswamy Stadium,K Hariharan,DJ Harper,NaN
257,258,2011,Kolkata,2011-04-22,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,9,CH Gayle,Eden Gardens,SS Hazare,RB Tiffin,NaN
290,291,2011,Bangalore,2011-05-14,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,1,Royal Challengers Bangalore,0,4,CH Gayle,M Chinnaswamy Stadium,RE Koertzen,RB Tiffin,NaN
316,317,2012,Bangalore,2012-04-10,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,42,0,L Balaji,M Chinnaswamy Stadium,S Ravi,RJ Tucker,NaN
343,344,2012,Kolkata,2012-04-28,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,47,0,G Gambhir,Eden Gardens,Asad Rauf,BR Doctrove,NaN
391,392,2013,Bangalore,2013-04-11,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,8,CH Gayle,M Chinnaswamy Stadium,Asad Rauf,AK Chaudhary,NaN
440,441,2013,Ranchi,2013-05-12,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,5,JH Kallis,JSCA International Stadium Complex,NJ Llong,K Srinath,NaN
467,468,2014,Sharjah,2014-04-24,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,2,0,CA Lynn,Sharjah Cricket Stadium,Aleem Dar,VA Kulkarni,NaN
505,506,2014,Kolkata,2014-05-22,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,30,0,RV Uthappa,Eden Gardens,AK Chaudhary,CK Nandan,NaN
521,522,2015,Kolkata,2015-04-11,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,3,CH Gayle,Eden Gardens,S Ravi,C Shamshuddin,NaN
549,550,2015,Bangalore,2015-05-02,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,7,Mandeep Singh,M Chinnaswamy Stadium,JD Cloete,PG Pathak,NaN
605,606,2016,Bangalore,2016-05-02,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,5,AD Russell,M Chinnaswamy Stadium,M Erasmus,S Ravi,NaN
623,624,2016,Kolkata,2016-05-16,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,9,V Kohli,Eden Gardens,CB Gaffaney,A Nand Kishore,NaN
638,7896,2018,Kolkata,08/04/18,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,4,SP Narine,Eden Gardens,C Shamshuddin,A.D Deshmukh,S Ravi
664,7922,2018,Bengaluru,29/04/18,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,6,CA Lynn,M Chinnaswamy Stadium,Nigel Llong,Anil Chaudhary,Virender Kumar Sharma
712,11153,2019,Bengaluru,05/04/19,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,5,AD Russell,M. Chinnaswamy Stadium,Anil Chaudhary,Chris Gaffaney,O Nandan
730,11326,2019,Kolkata,19/04/19,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Royal Challengers Bangalore,10,0,V Kohli,Eden Gardens,Ian Gould,Nitin Menon,Anil Dandekar

In [16]:
rdf.shape

(24, 18)

In [17]:
rdf[["team1","team2","toss_winner","toss_decision","winner"]]

,team1,team2,toss_winner,toss_decision,winner
26,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
44,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
59,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
87,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,Kolkata Knight Riders
133,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,Royal Challengers Bangalore
155,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore
177,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
216,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore
257,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore
290,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore
316,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
343,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,bat,Kolkata Knight Riders
391,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore
440,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
467,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
505,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders
521,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore
549,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore
605,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
623,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore
638,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
664,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
712,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders
730,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,Royal Challengers Bangalore

In [18]:
rdf[["team1","team2","toss_winner","toss_decision","winner"]].isnull().sum()

team1            0
team2            0
toss_winner      0
toss_decision    0
winner           0
dtype: int64

# 1

In [19]:
rdf[(rdf["toss_winner"]=="Royal Challengers Bangalore")&(rdf["toss_decision"]=="bat")]

Empty DataFrame
Columns: [id, season, city, date, team1, team2, toss_winner, toss_decision, result, dl_applied, winner, win_by_runs, win_by_wickets, player_of_match, venue, umpire1, umpire2, umpire3]
Index: []

In [20]:
rdf["winner"].value_counts()

Kolkata Knight Riders          14
Royal Challengers Bangalore    10
Name: winner, dtype: int64

# 2

toss winning captain decided bat first

# 3

In [21]:
data1.loc[450:600]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
450,2,2,Rising Pune Supergiant,Mumbai Indians,13,5,SPD Smith,BA Stokes,MJ McClenaghan,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
451,2,2,Rising Pune Supergiant,Mumbai Indians,13,6,SPD Smith,BA Stokes,MJ McClenaghan,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
452,2,2,Rising Pune Supergiant,Mumbai Indians,14,1,SPD Smith,BA Stokes,KA Pollard,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
453,2,2,Rising Pune Supergiant,Mumbai Indians,14,2,SPD Smith,BA Stokes,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
454,2,2,Rising Pune Supergiant,Mumbai Indians,14,3,BA Stokes,SPD Smith,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,3,1,Gujarat Lions,Kolkata Knight Riders,17,5,SK Raina,KD Karthik,PP Chawla,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
597,3,1,Gujarat Lions,Kolkata Knight Riders,17,6,KD Karthik,SK Raina,PP Chawla,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
598,3,1,Gujarat Lions,Kolkata Knight Riders,18,1,SK Raina,KD Karthik,TA Boult,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
599,3,1,Gujarat Lions,Kolkata Knight Riders,18,2,KD Karthik,SK Raina,TA Boult,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
600,3,1,Gujarat Lions,Kolkata Knight Riders,18,3,KD Karthik,SK Raina,TA Boult,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [22]:
data1.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [23]:
bat=data1[(data1["batting_team"]=='Kolkata Knight Riders')&(data1["bowling_team"]=="Royal Challengers Bangalore")&(data1["batsman"]=="KD Karthik")]

In [24]:
bat

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
151113,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,8,5,KD Karthik,N Rana,UT Yadav,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151114,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,8,6,KD Karthik,N Rana,UT Yadav,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151115,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,9,1,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151117,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,9,3,KD Karthik,N Rana,K Khejroliya,0,...,0,1,0,0,1,1,2,NaN,NaN,NaN
151119,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,9,5,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151120,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,9,6,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,1,1,2,NaN,NaN,NaN
151121,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,9,7,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
151124,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,10,3,KD Karthik,N Rana,UT Yadav,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151128,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,11,1,KD Karthik,N Rana,Washington Sundar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151132,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,11,5,KD Karthik,N Rana,Washington Sundar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
151133,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,11,6,KD Karthik,N Rana,Washington Sundar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151134,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,12,1,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151138,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,12,5,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151139,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,12,6,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151140,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,12,7,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151142,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,13,2,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151145,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,13,5,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,1,1,2,NaN,NaN,NaN
151146,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,13,6,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,1,1,2,NaN,NaN,NaN
151147,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,13,7,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
151148,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,13,8,KD Karthik,N Rana,K Khejroliya,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151150,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,2,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
151151,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,3,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
151152,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,4,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
151153,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,5,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151154,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,6,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151155,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,15,1,KD Karthik,N Rana,Washington Sundar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151159,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,15,5,KD Karthik,R Singh,Washington Sundar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151175,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,18,1,KD Karthik,AD Russell,CR Woakes,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151180,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,18,6,KD Karthik,R Vinay Kumar,CR Woakes,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
151181,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,18,7,KD Karthik,R Vinay Kumar,CR Woakes,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151183,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,19,2,KD Karthik,R Vinay Kumar,K Khejroliya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
151186,7896,2,Kolkata Knight Riders,Royal Challengers Bangalore,19,5,KD Karthik,R Vinay Kumar,K Khejroliya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
157337,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,17,7,KD Karthik,CA Lynn,Mohammed Siraj,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
157338,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,17,8,KD Karthik,CA Lynn,Mohammed Siraj,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
157341,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,18,3,KD Karthik,CA Lynn,TG Southee,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
157342,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,18,4,KD Karthik,CA Lynn,TG Southee,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
157343,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,18,5,KD Karthik,CA Lynn,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
157345,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,19,1,KD Karthik,CA Lynn,Mohammed Siraj,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
157346,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,19,2,KD Karthik,CA Lynn,Mohammed Siraj,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
157347,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,19,3,KD Karthik,CA Lynn,Mohammed Siraj,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
157348,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,19,4,KD Karthik,CA Lynn,Mohammed Siraj,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
157349,7922,2,Kolkata Knight Riders,Royal Challengers Bangalore,19,5,KD Karthik,CA Lynn,Mohammed Siraj,0,...,0,0,0,0,0,0,0,KD Karthik,caught,V Kohli
168866,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,12,4,KD Karthik,N Rana,P Negi,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168868,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,12,6,KD Karthik,N Rana,P Negi,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168869,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,13,1,KD Karthik,N Rana,N Saini,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
168870,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,13,2,KD Karthik,N Rana,N Saini,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168872,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,13,4,KD Karthik,N Rana,N Saini,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168875,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,1,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168877,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,3,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168879,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,14,5,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168887,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,16,1,KD Karthik,N Rana,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168891,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,16,5,KD Karthik,AD Russell,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
168892,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,16,6,KD Karthik,AD Russell,YS Chahal,0,...,0,1,0,0,1,1,2,NaN,NaN,NaN
168893,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,17,1,KD Karthik,AD Russell,N Saini,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168897,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,17,5,KD Karthik,AD Russell,N Saini,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168898,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,17,6,KD Karthik,AD Russell,N Saini,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
168899,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,17,7,KD Karthik,AD Russell,N Saini,0,...,0,0,0,0,0,0,0,KD Karthik,caught,YS Chahal

In [25]:
bat.shape

(57, 21)

In [26]:
bat.groupby(["over"])["batsman_runs"].sum()

over
8      1
9      5
10     1
11     6
12     3
13     7
14    14
15     2
16     2
17    17
18    12
19    12
Name: batsman_runs, dtype: int64

In [27]:
bat.groupby(["match_id"])["batsman_runs"].sum()

match_id
7896     39
7922     23
11153    20
Name: batsman_runs, dtype: int64

In [28]:
bat["batsman_runs"].sum()

82

In [29]:
(bat["batsman_runs"].sum())/3

27.333333333333332

In [30]:
bat["player_dismissed"].value_counts()

KD Karthik    2
Name: player_dismissed, dtype: int64

# 4

i didnt see any patterns in no of NO balls bowled in each match so i decided it manually

# 5

In [31]:
bat1=data1[(data1["batting_team"]=='Royal Challengers Bangalore')&(data1["bowling_team"]=="Kolkata Knight Riders")&(data1["batsman"]=="V Kohli")&(data1["batsman_runs"]==4)]

In [32]:
bat1

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
31203,134,2,Royal Challengers Bangalore,Kolkata Knight Riders,15,1,V Kohli,KP Pietersen,SC Ganguly,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
61104,258,2,Royal Challengers Bangalore,Kolkata Knight Riders,15,5,V Kohli,CH Gayle,L Balaji,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
61113,258,2,Royal Challengers Bangalore,Kolkata Knight Riders,17,1,V Kohli,CH Gayle,R Bhatia,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
61119,258,2,Royal Challengers Bangalore,Kolkata Knight Riders,18,1,V Kohli,CH Gayle,Iqbal Abdulla,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
68822,291,2,Royal Challengers Bangalore,Kolkata Knight Riders,5,1,V Kohli,LA Pomersbach,B Lee,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
68836,291,2,Royal Challengers Bangalore,Kolkata Knight Riders,7,2,V Kohli,AB de Villiers,Iqbal Abdulla,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
74697,317,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,6,V Kohli,AB de Villiers,JH Kallis,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
81177,344,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,2,V Kohli,CH Gayle,YK Pathan,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
81184,344,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,3,V Kohli,CH Gayle,B Lee,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
81186,344,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,5,V Kohli,CH Gayle,B Lee,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
92789,392,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,2,V Kohli,CH Gayle,R McLaren,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
92791,392,2,Royal Challengers Bangalore,Kolkata Knight Riders,6,4,V Kohli,CH Gayle,R McLaren,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
92799,392,2,Royal Challengers Bangalore,Kolkata Knight Riders,7,5,V Kohli,CH Gayle,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
92806,392,2,Royal Challengers Bangalore,Kolkata Knight Riders,8,6,V Kohli,CH Gayle,L Balaji,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
104475,441,1,Royal Challengers Bangalore,Kolkata Knight Riders,6,4,V Kohli,CH Gayle,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
104485,441,1,Royal Challengers Bangalore,Kolkata Knight Riders,8,2,V Kohli,CH Gayle,RN ten Doeschate,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
110997,468,2,Royal Challengers Bangalore,Kolkata Knight Riders,11,5,V Kohli,Yuvraj Singh,UT Yadav,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
111005,468,2,Royal Challengers Bangalore,Kolkata Knight Riders,13,1,V Kohli,Yuvraj Singh,JH Kallis,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
111006,468,2,Royal Challengers Bangalore,Kolkata Knight Riders,13,2,V Kohli,Yuvraj Singh,JH Kallis,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
111026,468,2,Royal Challengers Bangalore,Kolkata Knight Riders,16,4,V Kohli,Yuvraj Singh,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
120035,506,2,Royal Challengers Bangalore,Kolkata Knight Riders,4,5,V Kohli,YV Takawale,UT Yadav,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
120052,506,2,Royal Challengers Bangalore,Kolkata Knight Riders,7,4,V Kohli,YV Takawale,R Vinay Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
120061,506,2,Royal Challengers Bangalore,Kolkata Knight Riders,9,1,V Kohli,YV Takawale,R Vinay Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
130378,550,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,2,V Kohli,CH Gayle,UT Yadav,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
130384,550,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,1,V Kohli,CH Gayle,PJ Cummins,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
143249,606,1,Royal Challengers Bangalore,Kolkata Knight Riders,7,1,V Kohli,KL Rahul,UT Yadav,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
143258,606,1,Royal Challengers Bangalore,Kolkata Knight Riders,8,4,V Kohli,KL Rahul,PP Chawla,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
143285,606,1,Royal Challengers Bangalore,Kolkata Knight Riders,13,1,V Kohli,AB de Villiers,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
143287,606,1,Royal Challengers Bangalore,Kolkata Knight Riders,13,3,V Kohli,AB de Villiers,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
147564,624,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,4,V Kohli,CH Gayle,AD Russell,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
147574,624,2,Royal Challengers Bangalore,Kolkata Knight Riders,3,2,V Kohli,CH Gayle,AD Russell,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
147619,624,2,Royal Challengers Bangalore,Kolkata Knight Riders,10,5,V Kohli,AB de Villiers,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
147658,624,2,Royal Challengers Bangalore,Kolkata Knight Riders,17,1,V Kohli,AB de Villiers,Shakib Al Hasan,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
147664,624,2,Royal Challengers Bangalore,Kolkata Knight Riders,18,1,V Kohli,AB de Villiers,AS Rajpoot,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
151009,7896,1,Royal Challengers Bangalore,Kolkata Knight Riders,11,5,V Kohli,AB de Villiers,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
157179,7922,1,Royal Challengers Bangalore,Kolkata Knight Riders,12,6,V Kohli,Mandeep Singh,AD Russell,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
157187,7922,1,Royal Challengers Bangalore,Kolkata Knight Riders,14,1,V Kohli,Mandeep Singh,MG Johnson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
157193,7922,1,Royal Challengers Bangalore,Kolkata Knight Riders,15,1,V Kohli,Mandeep Singh,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
157199,7922,1,Royal Challengers Bangalore,Kolkata Knight Riders,16,1,V Kohli,Mandeep Singh,S Mavi,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
157202,7922,1,Royal Challengers Bangalore,Kolkata Knight Riders,16,4,V Kohli,Mandeep Singh,S Mavi,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168674,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,1,5,V Kohli,PA Patel,P Krishna,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168675,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,1,6,V Kohli,PA Patel,P Krishna,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168688,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,4,1,V Kohli,PA Patel,L Ferguson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168690,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,4,3,V Kohli,PA Patel,L Ferguson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168692,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,4,5,V Kohli,PA Patel,L Ferguson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168725,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,10,1,V Kohli,AB de Villiers,Kuldeep Yadav,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168734,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,11,4,V Kohli,AB de Villiers,PP Chawla,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168755,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,15,1,V Kohli,AB de Villiers,N Rana,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
168769,11153,1,Royal Challengers Bangalore,Kolkata Knight Riders,17,2,V Kohli,AB de Villiers,L Ferguson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173026,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,4,3,V Kohli,AD Nath,SP Narine,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173041,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,6,5,V Kohli,AD Nath,P Krishna,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173049,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,8,1,V Kohli,AD Nath,Kuldeep Yadav,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173051,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,8,3,V Kohli,AD Nath,Kuldeep Yadav,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173093,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,15,3,V Kohli,M Ali,P Krishna,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173106,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,17,3,V Kohli,MP Stoinis,H Gurney,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173108,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,17,5,V Kohli,MP Stoinis,H Gurney,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173120,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,19,3,V Kohli,MP Stoinis,P Krishna,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
173128,11326,1,Royal Challengers Bangalore,Kolkata Knight Riders,20,5,V Kohli,MP Stoinis,H Gurney,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [33]:
bat1.groupby(["match_id"])["batsman_runs"].count()

match_id
134      1
258      3
291      2
317      1
344      3
392      4
441      2
468      4
506      3
550      2
606      4
624      5
7896     1
7922     5
11153    9
11326    9
Name: batsman_runs, dtype: int64